# 0608 수업 정리
- 다중 분류

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Hello World")

Hello World


In [7]:
fish_all = pd.read_csv("Fish.csv")

fish_all

Species  Weight  Length   Height   Width
0     Bream   242.0    25.4  11.5200  4.0200
1     Bream   290.0    26.3  12.4800  4.3056
2     Bream   340.0    26.5  12.3778  4.6961
3     Bream   363.0    29.0  12.7300  4.4555
4     Bream   430.0    29.0  12.4440  5.1340
..      ...     ...     ...      ...     ...
154   Smelt    12.2    12.2   2.0904  1.3936
155   Smelt    13.4    12.4   2.4300  1.2690
156   Smelt    12.2    13.0   2.2770  1.2558
157   Smelt    19.7    14.3   2.8728  2.0672
158   Smelt    19.9    15.0   2.9322  1.8792

[159 rows x 5 columns]

In [8]:
pd.unique(fish_all["Species"])
# 각 열의 교유값을 보여준다.

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [9]:
fish_input = fish_all.drop(["Species"], axis=1)
# 가져온 데이터에서 물고기의 종류 부분만 제외시켜서 나머지 특성을 입력 변수로 만든다.

fish_input = fish_input.to_numpy()
fish_input[:5]

array([[242.    ,  25.4   ,  11.52  ,   4.02  ],
       [290.    ,  26.3   ,  12.48  ,   4.3056],
       [340.    ,  26.5   ,  12.3778,   4.6961],
       [363.    ,  29.    ,  12.73  ,   4.4555],
       [430.    ,  29.    ,  12.444 ,   5.134 ]])

In [59]:
fish_target = fish_all["Species"]

fish_target = fish_target.to_numpy()
fish_target[:5]

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream'], dtype=object)

In [60]:
from sklearn.model_selection import train_test_split


train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target,
                                                                      stratify=fish_target,
                                                                      random_state=42)


print(train_input.shape, train_target.shape)
print(test_input.shape, test_target.shape)

(119, 4) (119,)
(40, 4) (40,)


In [61]:
from sklearn.preprocessing import StandardScaler

scaler_std = StandardScaler()
scaler_std.fit(train_input)

train_scaled = scaler_std.transform(train_input)
test_scaled = scaler_std.transform(test_input)

print(train_scaled[:5])
print(test_scaled[:5])

[[-0.75628803 -0.66065677 -0.78015159 -0.45043644]
 [-0.45991057 -0.1248453  -0.4293487   0.03516919]
 [ 0.07356886  0.0212851   0.79541208  0.37481797]
 [ 1.54063728  1.0441979   2.29283234  1.34130358]
 [-0.87483902 -0.75807703 -0.80672937 -0.5697143 ]]
[[-0.84520127 -0.75807703 -0.70656438 -0.72566082]
 [-0.81556352 -0.72885095 -0.64263534 -0.58227616]
 [-0.96375225 -0.95291757 -0.82018436 -0.8716775 ]
 [-0.84520127 -0.95291757 -0.16608636 -0.95069758]
 [-0.93411451 -1.07956391 -0.40030299 -1.09731243]]


In [62]:
from sklearn.neighbors import KNeighborsClassifier

model_knr = KNeighborsClassifier(n_neighbors=7)
model_knr.fit(train_scaled, train_target)

KNeighborsClassifier(n_neighbors=7)

In [63]:
fish_prediction = model_knr.predict([test_scaled[26]])

print(fish_prediction)

['Perch']


In [64]:
indexs = model_knr.kneighbors([test_scaled[26]], return_distance=False)

train_target[indexs]

array([['Roach', 'Roach', 'Perch', 'Perch', 'Perch', 'Whitefish',
        'Whitefish']], dtype=object)

In [65]:
print(model_knr.classes_) # 모델이 저장하고 있는 클래스

fish_proba = model_knr.predict_proba([test_scaled[25]])
# predict_proba() 함수는 해당 데이터가 나올 클래스들의 확률을 나타낸다.
print(np.round(fish_proba, decimals=2))

['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
[[0.   0.   0.86 0.   0.   0.   0.14]]


In [66]:
test_target[25] # 25번째 데이의 실제 물고기

'Perch'

# 0609 수업 정리
- 만든 모델의 평가

In [77]:
index_input = int(input("범호를 입력 하세요. (0~39) : "))
fish_proba = model_knr.predict_proba([test_scaled[index_input]])


print(f"\n{index_input}번째 테스트 데이터는")

if(fish_proba[0][0] != 0):
    print(f"도미(Bream) : {fish_proba[0][0] * 100 : .2f}%")
if(fish_proba[0][1] != 0):
    print(f"곤들매기(Parkki) : {fish_proba[0][1] * 100 : .2f}%")
if(fish_proba[0][2] != 0):
    print(f"농어(Perch) : {fish_proba[0][2] * 100 : .2f}%")
if(fish_proba[0][3] != 0):
    print(f"강꼬치기(Pike) : {fish_proba[0][3] * 100 : .2f}%")
if(fish_proba[0][4] != 0):
    print(f"로치(Roach) : {fish_proba[0][4] * 100 : .2f}%")
if(fish_proba[0][5] != 0):
    print(f"빙어(Smelt) : {fish_proba[0][5] * 100 : .2f}%")
if(fish_proba[0][6] != 0):
    print(f"송어(Whitesifh) : {fish_proba[0][6] * 100 : .2f}%")
    
print("의 확률입니다.")

범호를 입력 하세요. (0~39) : 26

26번째 테스트 데이터는
농어(Perch) :  42.86%
로치(Roach) :  28.57%
송어(Whitesifh) :  28.57%
의 확률입니다.


In [68]:
print(f"테스트 데이터로 평가한 모델의 정확도는 {model_knr.score(test_input, test_target) : .2f}입니다.")

테스트 데이터로 평가한 모델의 정확도는  0.35입니다.


In [76]:
print("모델이 잘못 분류한 데이터는")

for n, i in enumerate(test_scaled):
#     print(i)
    if (model_knr.predict([i])[0] != test_target[n]):
        print(f"{n : 2d}번째")
        
print("입니다.")

모델이 잘못 분류한 데이터는
 0번째
 5번째
 9번째
 10번째
 11번째
 14번째
 16번째
 18번째
 23번째
 26번째
 35번째
입니다.
