In [82]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler

import pickle
import joblib

print("Hello World")

Hello World


In [3]:
fishData = pd.read_csv("./Fish.csv")

fishData

Species  Weight  Length   Height   Width
0     Bream   242.0    25.4  11.5200  4.0200
1     Bream   290.0    26.3  12.4800  4.3056
2     Bream   340.0    26.5  12.3778  4.6961
3     Bream   363.0    29.0  12.7300  4.4555
4     Bream   430.0    29.0  12.4440  5.1340
..      ...     ...     ...      ...     ...
154   Smelt    12.2    12.2   2.0904  1.3936
155   Smelt    13.4    12.4   2.4300  1.2690
156   Smelt    12.2    13.0   2.2770  1.2558
157   Smelt    19.7    14.3   2.8728  2.0672
158   Smelt    19.9    15.0   2.9322  1.8792

[159 rows x 5 columns]

# 농어의 무게

In [6]:
fishPerch = fishData[fishData["Species"] == "Perch"]

fishPerch

Species  Weight  Length   Height   Width
72    Perch     5.9     8.4   2.1120  1.4080
73    Perch    32.0    13.7   3.5280  1.9992
74    Perch    40.0    15.0   3.8240  2.4320
75    Perch    51.5    16.2   4.5924  2.6316
76    Perch    70.0    17.4   4.5880  2.9415
77    Perch   100.0    18.0   5.2224  3.3216
78    Perch    78.0    18.7   5.1992  3.1234
79    Perch    80.0    19.0   5.6358  3.0502
80    Perch    85.0    19.6   5.1376  3.0368
81    Perch    85.0    20.0   5.0820  2.7720
82    Perch   110.0    21.0   5.6925  3.5550
83    Perch   115.0    21.0   5.9175  3.3075
84    Perch   125.0    21.0   5.6925  3.6675
85    Perch   130.0    21.3   6.3840  3.5340
86    Perch   120.0    22.0   6.1100  3.4075
87    Perch   120.0    22.0   5.6400  3.5250
88    Perch   130.0    22.0   6.1100  3.5250
89    Perch   135.0    22.0   5.8750  3.5250
90    Perch   110.0    22.0   5.5225  3.9950
91    Perch   130.0    22.5   5.8560  3.6240
92    Perch   150.0    22.5   6.7920  3.6240
93    Perch   145.0    22.7   5.9532  3.6300
94    Perch   150.0    23.0   5.2185  3.6260
95    Perch   170.0    23.5   6.2750  3.7250
96    Perch   225.0    24.0   7.2930  3.7230
97    Perch   145.0    24.0   6.3750  3.8250
98    Perch   188.0    24.6   6.7334  4.1658
99    Perch   180.0    25.0   6.4395  3.6835
100   Perch   197.0    25.6   6.5610  4.2390
101   Perch   218.0    26.5   7.1680  4.1440
102   Perch   300.0    27.3   8.3230  5.1373
103   Perch   260.0    27.5   7.1672  4.3350
104   Perch   265.0    27.5   7.0516  4.3350
105   Perch   250.0    27.5   7.2828  4.5662
106   Perch   250.0    28.0   7.8204  4.2042
107   Perch   300.0    28.7   7.5852  4.6354
108   Perch   320.0    30.0   7.6156  4.7716
109   Perch   514.0    32.8  10.0300  6.0180
110   Perch   556.0    34.5  10.2565  6.3875
111   Perch   840.0    35.0  11.4884  7.7957
112   Perch   685.0    36.5  10.8810  6.8640
113   Perch   700.0    36.0  10.6091  6.7408
114   Perch   700.0    37.0  10.8350  6.2646
115   Perch   690.0    37.0  10.5717  6.3666
116   Perch   900.0    39.0  11.1366  7.4934
117   Perch   650.0    39.0  11.1366  6.0030
118   Perch   820.0    39.0  12.4313  7.3514
119   Perch   850.0    40.0  11.9286  7.1064
120   Perch   900.0    40.0  11.7300  7.2250
121   Perch  1015.0    40.0  12.3808  7.4624
122   Perch   820.0    40.0  11.1350  6.6300
123   Perch  1100.0    42.0  12.8002  6.8684
124   Perch  1000.0    43.0  11.9328  7.2772
125   Perch  1100.0    43.0  12.5125  7.4165
126   Perch  1000.0    43.5  12.6040  8.1420
127   Perch  1000.0    44.0  12.4888  7.5958

In [32]:
perchLength = fishPerch["Length"].to_numpy()
perchLength = perchLength.reshape(-1, 1)

perchWeight = fishPerch["Weight"].to_numpy()
perchWeight = perchWeight.reshape(-1, 1)

perchTrainInput, perchTestInput, perchTrainTarget, perchTestTarget = train_test_split(perchLength, perchWeight, random_state=42)

In [33]:
polyD2 = PolynomialFeatures(degree=2, include_bias=False)

perchTrainInput = polyD2.fit_transform(perchTrainInput)
perchTestInput = polyD2.fit_transform(perchTestInput)
perchTrainInput

array([[  19.6 ,  384.16],
       [  22.  ,  484.  ],
       [  18.7 ,  349.69],
       [  17.4 ,  302.76],
       [  36.  , 1296.  ],
       [  25.  ,  625.  ],
       [  40.  , 1600.  ],
       [  39.  , 1521.  ],
       [  43.  , 1849.  ],
       [  22.  ,  484.  ],
       [  20.  ,  400.  ],
       [  22.  ,  484.  ],
       [  24.  ,  576.  ],
       [  27.5 ,  756.25],
       [  43.  , 1849.  ],
       [  40.  , 1600.  ],
       [  24.  ,  576.  ],
       [  21.  ,  441.  ],
       [  27.5 ,  756.25],
       [  40.  , 1600.  ],
       [  32.8 , 1075.84],
       [  26.5 ,  702.25],
       [  36.5 , 1332.25],
       [  13.7 ,  187.69],
       [  22.7 ,  515.29],
       [  15.  ,  225.  ],
       [  37.  , 1369.  ],
       [  35.  , 1225.  ],
       [  28.7 ,  823.69],
       [  23.5 ,  552.25],
       [  39.  , 1521.  ],
       [  21.  ,  441.  ],
       [  23.  ,  529.  ],
       [  22.  ,  484.  ],
       [  44.  , 1936.  ],
       [  22.5 ,  506.25],
       [  19.  ,  361.  ],
 

In [34]:
perchModel = LinearRegression()
perchModel.fit(perchTrainInput, perchTrainTarget),

(LinearRegression(),)

In [38]:
perchModel.predict([[60, 60 ** 2]])

array([[2474.17030581]])

In [36]:
perchModel.score(perchTestInput, perchTestTarget)

0.9775935108325123

In [37]:
modelFile = open("./fishMarketPerchModel.pkl", "wb")
pickle.dump(perchModel, modelFile)

modelFile.close()

print("End")

End


# 도미인지 방어인지..?

In [55]:
# 도미 데이터
fishBream = fishData[fishData["Species"] == "Bream"]
breamLength = fishBream["Length"].to_numpy()
breamLength = breamLength.reshape(-1, 1)

breamWeight = fishBream["Weight"].to_numpy()
breamWeight = breamWeight.reshape(-1, 1)

In [56]:
# 빙어 데이터
fishSmelt = fishData[fishData["Species"] == "Smelt"]

smeltLength = fishSmelt["Length"].to_numpy()
smeltLength = smeltLength.reshape(-1, 1)

smeltWeight = fishSmelt["Weight"].to_numpy()
smeltWeight = smeltWeight.reshape(-1, 1)

smeltWeight

array([[ 6.7],
       [ 7.5],
       [ 7. ],
       [ 9.7],
       [ 9.8],
       [ 8.7],
       [10. ],
       [ 9.9],
       [ 9.8],
       [12.2],
       [13.4],
       [12.2],
       [19.7],
       [19.9]])

In [61]:
lengthBreamSmelt = np.concatenate([breamLength, smeltLength], axis = 0)
print(lengthBreamSmelt.shape)

lengthBreamSmelt

(49, 1)


array([[25.4],
       [26.3],
       [26.5],
       [29. ],
       [29. ],
       [29.7],
       [29.7],
       [30. ],
       [30. ],
       [30.7],
       [31. ],
       [31. ],
       [31.5],
       [32. ],
       [32. ],
       [32. ],
       [33. ],
       [33. ],
       [33.5],
       [33.5],
       [34. ],
       [34. ],
       [34.5],
       [35. ],
       [35. ],
       [35. ],
       [35. ],
       [36. ],
       [36. ],
       [37. ],
       [38.5],
       [38.5],
       [39.5],
       [41. ],
       [41. ],
       [ 9.8],
       [10.5],
       [10.6],
       [11. ],
       [11.2],
       [11.3],
       [11.8],
       [11.8],
       [12. ],
       [12.2],
       [12.4],
       [13. ],
       [14.3],
       [15. ]])

In [62]:
weightBreamSmelt = np.concatenate([breamWeight, breamWeight], axis=0)
print(weightBreamSmelt.shape)

weightBreamSmelt

(49, 1)


array([[ 242. ],
       [ 290. ],
       [ 340. ],
       [ 363. ],
       [ 430. ],
       [ 450. ],
       [ 500. ],
       [ 390. ],
       [ 450. ],
       [ 500. ],
       [ 475. ],
       [ 500. ],
       [ 500. ],
       [ 340. ],
       [ 600. ],
       [ 600. ],
       [ 700. ],
       [ 700. ],
       [ 610. ],
       [ 650. ],
       [ 575. ],
       [ 685. ],
       [ 620. ],
       [ 680. ],
       [ 700. ],
       [ 725. ],
       [ 720. ],
       [ 714. ],
       [ 850. ],
       [1000. ],
       [ 920. ],
       [ 955. ],
       [ 925. ],
       [ 975. ],
       [ 950. ],
       [   6.7],
       [   7.5],
       [   7. ],
       [   9.7],
       [   9.8],
       [   8.7],
       [  10. ],
       [   9.9],
       [   9.8],
       [  12.2],
       [  13.4],
       [  12.2],
       [  19.7],
       [  19.9]])

In [65]:
data_input = np.concatenate([lengthBreamSmelt, weightBreamSmelt], axis=1)
data_input

array([[  25.4,  242. ],
       [  26.3,  290. ],
       [  26.5,  340. ],
       [  29. ,  363. ],
       [  29. ,  430. ],
       [  29.7,  450. ],
       [  29.7,  500. ],
       [  30. ,  390. ],
       [  30. ,  450. ],
       [  30.7,  500. ],
       [  31. ,  475. ],
       [  31. ,  500. ],
       [  31.5,  500. ],
       [  32. ,  340. ],
       [  32. ,  600. ],
       [  32. ,  600. ],
       [  33. ,  700. ],
       [  33. ,  700. ],
       [  33.5,  610. ],
       [  33.5,  650. ],
       [  34. ,  575. ],
       [  34. ,  685. ],
       [  34.5,  620. ],
       [  35. ,  680. ],
       [  35. ,  700. ],
       [  35. ,  725. ],
       [  35. ,  720. ],
       [  36. ,  714. ],
       [  36. ,  850. ],
       [  37. , 1000. ],
       [  38.5,  920. ],
       [  38.5,  955. ],
       [  39.5,  925. ],
       [  41. ,  975. ],
       [  41. ,  950. ],
       [   9.8,    6.7],
       [  10.5,    7.5],
       [  10.6,    7. ],
       [  11. ,    9.7],
       [  11.2,    9.8],


In [83]:
scalerStd = StandardScaler()
scalerStd.fit(data_input)

data_input = scalerStd.transform(data_input)

In [84]:
targetBream = np.ones(35)
targetSmelt = np.zeros(14)

data_target = np.concatenate([targetBream, targetSmelt])
print(data_target.shape)

(49,)


In [85]:
trainInput, testInput, trainTarget, testTarget = train_test_split(data_input, data_target, stratify=data_target, random_state=42)

print(trainTarget)
print(testTarget)

[1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1.
 0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1.]
[0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1.]


In [86]:
breamSmeltModel = KNeighborsRegressor()
breamSmeltModel.fit(trainInput, trainTarget)

KNeighborsRegressor()

In [92]:
input = scalerStd.transform([[25, 150]])
breamSmeltModel.kneighbors(input, return_distance=False)

array([[21, 14, 34, 32,  5]], dtype=int64)

In [93]:
breamSmeltModel.score(testInput, testTarget)

1.0

In [94]:
modelFile = open("./fishMarketBreamSmeltModel.pkl", "wb")
pickle.dump(breamSmeltModel, modelFile)

modelFile.close()

print("End")

End


In [95]:
modelFile = open("./fishMarketBreamSmeltScaled.pkl", "wb")
pickle.dump(scalerStd, modelFile)
modelFile.close()

print("End")

End
